include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.config.dart"
    - "**.gform.dart"
    - "**.sql"
    - lib/src/common/l10n/*
    - supabase/*

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    lines_longer_than_80_chars: false