name: urolit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.4.0
  fpdart: ^0.6.0
  get_it: ^7.2.0
  intl: ^0.18.1
  ionicons: ^0.2.2
  json_annotation: ^4.7.0
  path: ^1.8.2
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1
  reactive_date_time_picker: ^3.0.0
  reactive_dropdown_search: ^3.0.0
  reactive_forms: ^16.0.0
  reactive_forms_annotations: ^4.0.0
  mask_text_input_formatter: ^2.5.0
  shared_preferences: ^2.0.15
  stream_transform: ^2.1.0
  test: ^1.22.2
  uuid: ^3.0.7
  pdf: ^3.10.4
  open_file: ^3.3.2
  http: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flash: ^3.0.5+1
  desktop_window: ^0.4.0
  window_manager: ^0.3.7
  hovering: ^1.0.4
  logger: ^2.0.2+1
  package_info_plus: ^4.2.0
  flutter_gutter: ^1.0.0
  collection: ^1.17.2
  im_stepper: ^1.0.1+1
  auto_route: ^7.8.4

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.1.0+1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  reactive_forms_generator: ^4.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: false

  assets:
   - assets/l10n/

flutter_gen:
  output: lib/assets # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flare_flutter: true
    rive: true
    lottie: true